study/login/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('home/signup/', signup, name='signup'),
    path('home/login/', login, name='login'),
    path('home/logout/', logout, name='logout'),
    path('home/', home, name='home'),
]

study/post/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.list, name='list'),
    path('write/',views.write, name='write'),
    path('show/<int:post_id>/', views.show, name='show'),
] 

study/study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('post/', include('post.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/login/models.py
from django.db import models

# Create your models here.

study/post/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=200)
    content=models.TextField()
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Image(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    image=models.ImageField(upload_to = 'images/', null=True, blank =True)
    

study/post/forms.py
from django import forms
from .models import Post, Image

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','content']

study/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password1'],
                email=request.POST['email'],
            )
            auth.login(request, user)
            return redirect('list')
        return render(request, 'signup.html')
    return render(request, 'singup.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('list')
        else:
            return render(request, 'login.html',{'error':'username or password is incorrect.'})
    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('home')

def home(request):
    return render(request, 'home.html')

study/post/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Post, Image
from .forms import PostForm
# Create your views here.

# @require_POST
# @login_required

def list(request):
    # post = get_object_or_404(Post, pk=pk)
    # if request.user == post.user:
    posts = Post.objects.all()
    return render(request,'main.html', {'posts':posts})

def write(request):
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            for img in request.FILES.getlist('image', None):
                Image.objects.create(post=post, image=img)
            return redirect('list')
    else:
        form=PostForm()
        return render(request,'write.html', {'form':form})
    
def show(request, post_id):
    post=get_object_or_404(Post, pk=post_id)
    # post = Post.objects.filter(Post, pk =post_id)
    images = Image.objects.filter(post=post)
    # post = Post.objects.prefetch_related('image_set').get(pk=post_id)
    return render(request, 'detail.html',{'post':post, 'images':images})

study/login/templates/base.html
{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Website{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {%block extrahead%}{%endblock%}
</head>
<body>
    {%block content%}
    {%endblock%}
</body>
</html> {% endcomment %}

study/login/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Website{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {%block extrahead%}{%endblock%}
</head>
<body>
    {%block content%}
    <div>
        <h3><a href="signup">회원가입</a></h3>
        <h3><a href="login">로그인</a></h3>
        <h3><a href="logout">로그아웃</a></h3>
        {% if user.is_authenticated %}
            <p>{{user}}님, 환영합니다!</p>
        {% else %}
            <p>로그인해주세요.</p>
        {% endif %}
    </div>
    {%endblock%}
</body>
</html>






{% comment %} {%extends 'base.html'%}
{%load bootstrap4%}
{%block content%}
<div>
    <h3><a href="signup">회원가입</a></h3>
    <h3><a href="login">로그인</a></h3>
    <h3><a href="logout">로그아웃</a></h3>
    {% if user.is_authenticated %}
        <p>{{user}}님, 환영합니다!</p>
    {% else %}
        <p>로그인해주세요.</p>
    {% endif %}
</div>
{%endblock%} {% endcomment %}

study/login/templates/index.html
{% extends "home.html" %}

{%block title%}My Home Page{%endblock%}

{%block extrahead%}
    <link rel="stylesheet" href="{% static "css/index.css" %}">
{%endblock%}

{%block content%}
    <h1>Welcome to my website!</h1>
{%endblock%}

study/login/templates/login.html
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="wrapper">
    <div style="text-align: center;">
        <h1>로그인</h1>
        <form method="POST">
            {% csrf_token %}
            아이디:
            <br>
            <input name="username" type="text">
            <br>
            비밀번호:
            <br>
            <input name="password" type="password">
            <br><br>
            <input type="submit" class="btn btn-primary" value="Login">
        </form>
    </div>
</div>
{% endblock %}

study/login/templates/singup.html
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="wrapper" style="text-align: center;">
    <h1>회원가입</h1>
    <form method="POST">
        {% csrf_token %}
        아이디: <br>
        <input name="username" type="text">
        <br>
        비밀번호: <br>
        <input name="password1" type="password">
        <br>
        비밀번호 확인: <br>
        <input name="password2" type="password">
        <br>
        이메일: <br>
        <input name="email" type="email">
        <br><br>
        <input type="submit" class="btn btn-primary" value="Sign Up">
    </form>
</div>
{% endblock %}

study/post/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }}</title>
</head>
<body>
    <h1>제목 : {{ post.title }}</h1>
    <p>내용 : {{ post.content }}</p>
    {% for image in images %}
        <img src = "{{image.image.url}}" alt="Image">
    {% endfor %}

    <button><a href="{% url 'list' %}">목록</a></button>
</body>
</html>

study/post/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <title>Post List</title>
</head>
<body>
{% if user.is_authenticated %}
<h3><a href="http://127.0.0.1:8000/login/home/logout/">로그아웃</a></h3>
<p>{{user}}님, 환영합니다!</p>
<h1>목록</h1>
<ul>
    {% for post in posts %}
    {%if request.user == post.user%}
    <li><a href="{% url 'show' post.id %}">{{ post.title }}</a></li>
    {%endif%}
    {% endfor %}
</ul>
<a href="{% url 'write' %}">글 작성</a>
{% else %}
<h3><a href="http://127.0.0.1:8000/login/home/">메인페이지</a></h3>
<p>로그인해주세요.</p>
{% endif %}
</body>
</html>

study/post/templates/write.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Post</title>
</head>
<body>
    <h1>글 작성</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input multiple type="file" name="image" aceept="image/*" id="id_image">
        <button type="submit">저장</button>
    </form>
</body>
</html>